### ISSUE TITLE
--replace flag, check if bidsmreye output has been produced already and skip processing of files that already have data [ENH] 

### ISSUE THREAD

**Issue by Michael-Sun** [cpp-lln-lab/bidsMReye#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

Running bidsmreye on a cluster compute gpu node can run into issues if the process gets killed because of memory errors, timeout, or other miscellaneous issues (e.g., administration-level malicious code detection wrongly kills your process). It would be good if bidsmreye can pick up where it left off instead of starting processing all over again.

**Comment by Remi-Gau** [comment]
yeah I was thinking of possibly using a proper workflow manager for this. 
nipype / pydra or bidsnake?

this may not happen fast but it would be useful to have

**Comment by Remi-Gau** [comment]
for now I may make the default behavior to reuse pre-existing files and pass a `--force` flag to overwrite previous results

**Comment by Remi-Gau** [comment]
Not sure if you are using it. But splitting the processing by running one action at a time may help a bit as well. 

https://bidsmreye.readthedocs.io/en/latest/usage_notes.html#named-arguments

**Comment by Remi-Gau** [comment]
> for now I may make the default behavior to reuse pre-existing files and pass a `--force` flag to overwrite previous results

files that already have an output should now be skipped unless the --force argument is passed in the CLI
