### ISSUE TITLE
Create autogenerated methods

### ISSUE THREAD

**Issue by Naubody** [cpp-lln-lab/bidsMReye#67]
The goal is to write a bidsMReye boilerplate (i.e. autogenerated methods section) to improve reproducibility and consistency in reporting (similar to fMRIprep).

Question: 
What's the current consensus on the use of the fMRIprep boilerplate in published articles? Are there many issues with journals flagging it as plagiarism? If so, what can we learn from it? What to avoid?

**Comment by Remi-Gau** [comment]
See the notes in this Nipreps page: https://www.nipreps.org/intro/transparency/#citation-boilerplates

Also there is this blogpost from the stanford team behind fmriprep: https://reproducibility.stanford.edu/copy-pasting-your-methods-section-is-good-actually/

What can we learn: point to those resources in a FAQ?
